name: VoteIT Java CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v3

    - name: JDK 17 installieren
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Kompilieren
      run: javac *.java

    - name: Unit-Tests ausführen
      run: java PostServiceTest

    - name: Paket erstellen (Artifact)
      if: success() # Nur wenn die Tests grün sind!
      uses: actions/upload-artifact@v4
      with:
        name: VoteIT-Lauffaehiges-Programm
        path: |
          *.class
          index.html
          logo.png
    
    - name: Docker Image bauen
      run: |
        docker build -t voteit-microservice .
        echo "Docker Image wurde erfolgreich lokal in der Pipeline erstellt."