name: VoteIT Java CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deliver:
    runs-on: ubuntu-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v3

    - name: JDK 17 installieren
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Kompilieren
      run: javac *.java

    # CD TEIL: Paket für die Auslieferung schnüren
    - name: Paket erstellen (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: VoteIT-Lauffaehiges-Programm
        path: |
          *.class
          index.html
          logo.png